@echo off
rem init-sandbox.cmd — Create sandbox directory structure for integration tests.
rem Run once before executing: mvn verify -P sandbox-it
rem
rem Creates:
rem   tests\sandbox\Data\        — place for NSF fixtures (generated by SandboxFixtureBuilder)
rem   tests\sandbox\id\          — place for sandbox.id (no password, see ADR-3)
rem   tests\sandbox\notes.ini    — minimal Notes config pointing at sandbox Data dir
rem
rem IMPORTANT: Never use production Notes databases in tests (see ADR-3).

setlocal

set "PROJECT_DIR=%~dp0.."
set "SANDBOX_DIR=%PROJECT_DIR%\tests\sandbox"
set "SANDBOX_DATA=%SANDBOX_DIR%\Data"
set "SANDBOX_ID=%SANDBOX_DIR%\id"

echo.
echo === hcl-notes-mcp sandbox init ===
echo Sandbox : %SANDBOX_DIR%
echo.

rem Create directory structure
if not exist "%SANDBOX_DATA%" mkdir "%SANDBOX_DATA%"
if not exist "%SANDBOX_ID%"  mkdir "%SANDBOX_ID%"

rem Generate minimal notes.ini if not present
if not exist "%SANDBOX_DIR%\notes.ini" (
    echo Directory=%SANDBOX_DATA%\> "%SANDBOX_DIR%\notes.ini"
    echo KitType=2>> "%SANDBOX_DIR%\notes.ini"
    echo USING_LOCAL_SHARED_MEM=0>> "%SANDBOX_DIR%\notes.ini"
    echo DisablePopups=1>> "%SANDBOX_DIR%\notes.ini"
    echo NoAutoUpdate=1>> "%SANDBOX_DIR%\notes.ini"
    echo [Notes]>> "%SANDBOX_DIR%\notes.ini"
    echo Created %SANDBOX_DIR%\notes.ini
) else (
    echo notes.ini already exists, skipping.
)

echo.
echo Sandbox structure ready.
echo.
echo Next steps:
echo   1. Copy (or create) a password-free Notes ID to: tests\sandbox\id\sandbox.id
echo   2. Run SandboxFixtureBuilder to populate NSF fixtures:
echo        mvn exec:java -Dexec.mainClass=com.hcl.notes.mcp.sandbox.SandboxFixtureBuilder ^
echo            -Dexec.args="%SANDBOX_DIR%"
echo   3. Run integration tests: mvn verify -P sandbox-it
endlocal
